# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-cli/Makefile 394023 2015-08-12 16:10:30Z feld $

PKGNAMESUFFIX=	-cli

COMMENT=	MooseFS command line interface

LICENSE=	GPLv2

MFS_COMPONENT=	cli

MASTERDIR=	${.CURDIR}/../moosefs-master

PLIST_FILES=	bin/mfscli

.include "${MASTERDIR}/Makefile"
