# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs3-chunkserver/Makefile 419134 2016-07-26 16:56:05Z feld $

PKGNAMESUFFIX=	-chunkserver

COMMENT=	MooseFS data storage and synchronization component

LICENSE=	GPLv2

MFS_COMPONENT=	chunkserver

MASTERDIR=	${.CURDIR}/../moosefs3-master

.include "${MASTERDIR}/Makefile"
