# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-cgiserv/Makefile 394023 2015-08-12 16:10:30Z feld $

PKGNAMESUFFIX=	-cgiserv

COMMENT=	MooseFS CGI webserver

LICENSE=	GPLv2

MFS_COMPONENT=	cgiserv

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
