# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs3-cgiserv/Makefile 419134 2016-07-26 16:56:05Z feld $

PKGNAMESUFFIX=	-cgiserv

COMMENT=	MooseFS CGI webserver

LICENSE=	GPLv2

MFS_COMPONENT=	cgiserv

MASTERDIR=	${.CURDIR}/../moosefs3-master

.include "${MASTERDIR}/Makefile"
