# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-client/Makefile 394023 2015-08-12 16:10:30Z feld $

PKGNAMESUFFIX=	-client

COMMENT=	MooseFS client tools

LICENSE=	GPLv2

MFS_COMPONENT=	client

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
