# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-chunkserver/Makefile 394023 2015-08-12 16:10:30Z feld $

PKGNAMESUFFIX=	-chunkserver

COMMENT=	MooseFS data storage and synchronization component

LICENSE=	GPLv2

MFS_COMPONENT=	chunkserver

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
