# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-cgi/Makefile 394023 2015-08-12 16:10:30Z feld $

PKGNAMESUFFIX=	-cgi

COMMENT=	MooseFS CGI interface

LICENSE=	GPLv2

MFS_COMPONENT=	cgi

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
