# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-cli/Makefile 410208 2016-03-05 20:10:34Z feld $

PKGNAMESUFFIX=	-cli

COMMENT=	MooseFS command line interface

LICENSE=	GPLv2

MFS_COMPONENT=	cli

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
