# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-netdump/Makefile 394023 2015-08-12 16:10:30Z feld $

PKGNAMESUFFIX=	-netdump

COMMENT=	MooseFS network packet dump utility

LICENSE=	GPLv2

MFS_COMPONENT=	netdump

MASTERDIR=	${.CURDIR}/../moosefs-master

PLIST_FILES=	sbin/mfsnetdump \
		man/man8/mfsnetdump.8.gz

.include "${MASTERDIR}/Makefile"
