# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-netdump/Makefile 410208 2016-03-05 20:10:34Z feld $

PKGNAMESUFFIX=	-netdump

COMMENT=	MooseFS network packet dump utility

LICENSE=	GPLv2

MFS_COMPONENT=	netdump

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
