# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs3-cgi/Makefile 419132 2016-07-26 16:50:55Z feld $

PKGNAMESUFFIX=	-cgi

COMMENT=	MooseFS CGI interface

LICENSE=	GPLv2

MFS_COMPONENT=	cgi

MASTERDIR=	${.CURDIR}/../moosefs3-master

.include "${MASTERDIR}/Makefile"
