# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs3-cli/Makefile 419134 2016-07-26 16:56:05Z feld $

PKGNAMESUFFIX=	-cli

COMMENT=	MooseFS command line interface

LICENSE=	GPLv2

MFS_COMPONENT=	cli

MASTERDIR=	${.CURDIR}/../moosefs3-master

.include "${MASTERDIR}/Makefile"
