# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs-metalogger/Makefile 394023 2015-08-12 16:10:30Z feld $

PKGNAMESUFFIX=	-metalogger

COMMENT=	MooseFS metadata backup server

LICENSE=	GPLv2

MFS_COMPONENT=	metalogger

MASTERDIR=	${.CURDIR}/../moosefs-master

.include "${MASTERDIR}/Makefile"
