# Created by: Jakub Kruszona-Zawadzki <acid@moosefs.com> ; Based on port created by: Chifeng Qu <chifeng@gmail.com>
# $FreeBSD: head/sysutils/moosefs2-metalogger/Makefile 418199 2016-07-07 20:58:23Z feld $

PKGNAMESUFFIX=	-metalogger

COMMENT=	MooseFS metadata backup server

LICENSE=	GPLv2

MFS_COMPONENT=	metalogger

MASTERDIR=	${.CURDIR}/../moosefs2-master

.include "${MASTERDIR}/Makefile"
